### ISSUE TITLE
Delete by _id (mongoose)

### ISSUE THREAD

**Issue by cwolberg** [adrianb13/GoogleBooks#1]
Function being tested: User is attempting to delete specific book

Initial System State: Saved Page (contains list of saved books)

Input: delete button for specific project is clicked

Expected Output: specific deleted book is removed from saved list

Current Output: book is not deleted, status: OK, but deletedCount: 0
so it's connecting but not being able to locate the specific id to be deleted
using the built-in Mongoose id of "_id" to delete a specific item

Controller:
 remove: function(req, res) {
    db.Books
      .remove({_id: req.params._id})
      .then(dbModel => res.json(dbModel))
      .catch(err => res.status(422).json(err));

API.js in util folder:
deleteBook: function(bookId) {
    return axios.delete("/api/books/:id", bookId)
  }

Function:
handleDelete = book => {
    console.log(book._id)
    API.deleteBook(book._id)
    .then(res => {
      console.log(res.data)
      this.getSavedList()
    })
    .catch(err => console.log(err));
  }

**Comment by cwolberg** [comment]
i seemed to have gotten it to work on my end
it will delete books, but you have to refresh the page to see that it was deleted
api/util

 deleteBook: function(bookId) {
   return axios.delete("/api/books/" + bookId);
 }
controller

 remove: function(req, res) {
   db.Books
     .remove({_id: req.params.id})
     .then(dbModel => dbModel.remove())
     .then(dbModel => res.json(dbModel))
     .catch(err => res.status(422).json(err));
 }
i believe your controller needed that remove line and the params to be id, while the api was on the wrong route
let me know if that does anything

**Comment by adrianb13** [comment]
remove: function(req, res) {
db.Books
.remove({_id: req.params.id})
.then(dbModel => res.json(dbModel))
.catch(err => res.status(422).json(err));
}

this line below can be removed therefore allowing an auto refresh of the component since this is redundant to the line above in .remove()
**.then(dbModel => dbModel.remove())**

the only differnce which actually made it work was req.params.id WITHOUT the underscore before id.

**Comment by adrianb13** [comment]
Thanks for all your help on this!!!!
